title: Sengthai
email: sengthaite@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  tools:
    output: true
    permalink: /tool/:name


plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

safe: true