.PHONY: all check autogen rebuild build_runner deploy_web pip_install build_web gen_l10n gen_icon run_web doc run_doc run_llm help clean_asset

help: ## Show this help message
	@echo "Usage: make [target]"
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

upgrade_deps: ## Remove pubspec.lock and upgrade all dependencies to major versions
	rm ./pubspec.lock & flutter pub upgrade --major-versions

run_llm: ## Start llama-server with Gemma 4B model and tool support
	llama-server -hf google/gemma-4-E4B-it-qat-q4_0-gguf:Q4_0 -ngl 99 --tools all

run_web: ## Run Flutter app on local web server at port 7777
	flutter run -d web-server --web-hostname 0.0.0.0 --web-port 7777 --no-hot --verbose

doc: ## Generate Dart documentation
	dart doc .

run_doc: ## Serve generated documentation locally via dhttpd
	dart pub global activate dhttpd
	dart pub global run dhttpd --path doc/api

gen_icon: ## Generate app icons using icons_launcher
	dart run icons_launcher:create

gen_l10n: ## Generate Flutter localization files
	flutter gen-l10n

dist_linux: ## Package Linux release as .deb via flutter_distributor
	flutter_distributor release --name=dev --jobs=release-dev-linux-deb

build_linux: ## Build Flutter Linux release binary
	flutter build linux --release

build_web: ## Build Flutter web release with WASM support
	flutter build web --base-href=/ --wasm

autogen: ## Run Python autogeneration scripts
	python3 ./scripts/autogen.py

pip_install: ## Install Python script dependencies from requirements.txt
	pip install -r ./scripts/requirements.txt

clean: ## Remove autogenerated assets directory
	rm -rf ./assets/autogen_meta

clean_asset: ## Clean Assets Directory
	assets_cleaner clean

build_runner: ## Run build_runner to generate Dart code
	dart run build_runner build --delete-conflicting-outputs

check: ## Run unused code pruner and dependency validator
	flutter_prunekit unused_code && dependency_validator

add_assets: ## Add assets via asset_manager
	asset_manager add

all: clean autogen build_runner ## Full build: clean → autogen → build_runner

deploy_web: clean all gen_l10n ## Deploy web build to gh-pages branch
	# flutter pub global run dependency_validator
	flutter pub global run peanut --extra-args --base-href=/ --no-wasm --release
	git push origin --set-upstream gh-pages