// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv01r_afH1blcmvqrw3rF2S1519e_LydE',
    appId: '1:507932913683:web:a0861e5be0249d162bcfe6',
    messagingSenderId: '507932913683',
    projectId: 'sengthaite-4d518',
    authDomain: 'sengthaite-4d518.firebaseapp.com',
    storageBucket: 'sengthaite-4d518.firebasestorage.app',
    measurementId: 'G-CZ5H32WZST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5tuUGdZxqePKEWfQTZkkikRW4MDs69P4',
    appId: '1:507932913683:android:a594712d26ce87c32bcfe6',
    messagingSenderId: '507932913683',
    projectId: 'sengthaite-4d518',
    storageBucket: 'sengthaite-4d518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtmCSsNGtNCLDYPNEYUr6Ha0ZvepY8S8',
    appId: '1:507932913683:ios:8ae1d9d516d6c1e72bcfe6',
    messagingSenderId: '507932913683',
    projectId: 'sengthaite-4d518',
    storageBucket: 'sengthaite-4d518.firebasestorage.app',
    iosBundleId: 'com.example.sengthaiteBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjtmCSsNGtNCLDYPNEYUr6Ha0ZvepY8S8',
    appId: '1:507932913683:ios:8ae1d9d516d6c1e72bcfe6',
    messagingSenderId: '507932913683',
    projectId: 'sengthaite-4d518',
    storageBucket: 'sengthaite-4d518.firebasestorage.app',
    iosBundleId: 'com.example.sengthaiteBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv01r_afH1blcmvqrw3rF2S1519e_LydE',
    appId: '1:507932913683:web:f8ed46200951c1d42bcfe6',
    messagingSenderId: '507932913683',
    projectId: 'sengthaite-4d518',
    authDomain: 'sengthaite-4d518.firebaseapp.com',
    storageBucket: 'sengthaite-4d518.firebasestorage.app',
    measurementId: 'G-F6N8VLLX2Q',
  );

}