// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sengthaite_blog/shared/file/hivedir.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TempDirAdapter());
    registerAdapter(TempFileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TempDirAdapter());
    registerAdapter(TempFileAdapter());
  }
}
